### ISSUE TITLE
Compiled proto files not compatible?

### ISSUE THREAD

**Issue by rikardev** [wamuir/graft#14]
I'm trying to use graft 0.4.0 with tensorflow 2.12.0 running in a dockerimage ubuntu 22.04 and get this while running my tests:

```
[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/descriptor_database.cc:560] Invalid file descriptor data passed to EncodedDescriptorDatabase::Add().
[libprotobuf FATAL external/com_google_protobuf/src/google/protobuf/descriptor.cc:1986] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
```

Any ideas what this might be? Are the compiled protobufs not compatible with my environment?

**Comment by wamuir** [comment]
Are you using protoc?  If so, can you provide the output of `protoc --version`?

**Comment by wamuir** [comment]
Additionally, try something like the following (this is 22.04 w/ TF 2.12.0 and matching libprotobuf version):

```Dockerfile
FROM ubuntu:22.04

RUN apt-get update && apt-get install -y build-essential curl unzip

RUN curl -fSLs https://go.dev/dl/go1.20.4.linux-amd64.tar.gz \
  | tar -C /usr/local -xzf -

RUN curl -fSLs https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-2.12.0.tar.gz \
  | tar -C /usr/local -xzf -

RUN curl -fSLs https://github.com/protocolbuffers/protobuf/releases/download/v23.1/protoc-23.1-linux-x86_64.zip \
  > /tmp/protoc.zip \
  && unzip /tmp/protoc.zip -d /usr/local \
  && rm /tmp/protoc.zip

ENV PATH=$PATH:/usr/local/go/bin
ENV LIBRARY_PATH=$LIBRARY_PATH:/usr/local/lib
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

RUN ldconfig
```

**Comment by rikardev** [comment]
Was running protoc 21.4 before but had the same error after updating to 23.1 as you have. Have a similar setup in my Dockerfile but had the same error when trying yours. One line differs, I'm runnig M2 MacBook so had to do `FROM --platform=linux/amd64 ubuntu:22.04`. That got me little suspicious so asked a colleague to run the same test on his laptop (Intel MacBook) and it seemed to work there. So now I'm really confused and not sure how to proceed.

**Comment by wamuir** [comment]
Ahh, ok.  Looking over the error message above I'm now convinced that you are attempting to utilize libraries/binaries compiled for a different architecture: your M2 is arm64 not amd64.  These bindings will work perfectly fine with arm64 (and M2).  But, you'll need the appropriate arm64 build of libtensorflow which TF does not publish, at least not in the usual location (https://www.tensorflow.org/install/lang_c).  If you are going to use protoc then then also need the arm64 build, not the x86_64 build.

**Comment by rikardev** [comment]
The thing is, I though this wouldn't be a problem since I'm build everything in docker using amd64 ubuntu image. You're probably right though just not sure how it happens. Thanks for your help, I'll close this since everything seems to work for others.
