### ISSUE TITLE
Q: Segmentation fault when running example

### ISSUE THREAD

**Issue by nea** [wamuir/graft#25]
Ahoy there

First of all, thanks for this :) 

I tried to follow all instructions from here https://github.com/tensorflow/build/tree/master/golang_install_guide and use this package with the example program, but changed from tensorflow/tensorflow to graft. 
It compiles fine 👍 

But when I run it, it always throws a segmentation fault at session.go:150.

My test is only
```
package main

import (
	"fmt"
	tf "github.com/wamuir/graft/tensorflow"
	"github.com/wamuir/graft/tensorflow/op"
)

func main() {
	// Construct a graph with an operation that produces a string constant.
	s := op.NewScope()
	c := op.Const(s, "Hello from TensorFlow version "+tf.Version())
	graph, err := s.Finalize()
	if err != nil {
		panic(err)
	}

	// Execute the graph in a session.
	sess, err := tf.NewSession(graph, nil)
	if err != nil {
		panic(err)
	}
	output, err := sess.Run(nil, []tf.Output{c}, nil)
	if err != nil {
		panic(err)
	}
	fmt.Println(output[0].Value())
}
```

tf.NewSession leads to the error.

I installed libtensorflow on my Intel Mac via brew and it installed fine
```
==> libtensorflow: stable 2.15.0 (bottled)
C interface for Google's OS library for Machine Intelligence
https://www.tensorflow.org/
/usr/local/Cellar/libtensorflow/2.15.0 (36 files, 1.1GB) *
```

I used v0.7.0 from here to match the TF version, still the same segmentation fault, no matter what.

I am a little lost, as I do not see any other warning or errors aside from
```
2023-12-29 13:09:22.674132: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-29 13:09:22.679725: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:388] MLIR V1 optimization pass is not enabled
```

but I am not sure, if I have to manually build it or if there is another issue.

Any help or pointing in the right direction is highly appreciated.

Thanks a lot in advance

**Comment by wamuir** [comment]
Can you compile the following with gcc (e.g., `gcc hello_tf.c -ltensorflow -o hello_tf`):

```c
#include <stdio.h>
#include <tensorflow/c/c_api.h>

int main() {
  printf("Hello from TensorFlow C library version %s\n", TF_Version());
  return 0;
}
```

Then does running the resulting executable also result in a segfault?

**Comment by nea** [comment]
Ahoy

That prints out
```
tensorflow-image % gcc hello_tf.c -ltensorflow -o hello_tf
tensorflow-image % ./hello_tf
Hello from TensorFlow C library version 2.15.0
tensorflow-image % 
```


Best

**Comment by nea** [comment]
Additionally, here the stack:
```
SIGSEGV: segmentation violation
PC=0x1272c5e5d m=0 sigcode=1
signal arrived during cgo execution

goroutine 1 [syscall]:
runtime.cgocall(0x1001ce5b0, 0xc00013bce8)
        /usr/local/go/src/runtime/cgocall.go:157 +0x4b fp=0xc00013bcc0 sp=0xc00013bc88 pc=0x10000c04b
github.com/wamuir/graft/tensorflow._Cfunc_TF_SessionRun(0x6000010557a0, 0x0, 0x0, 0x0, 0x0, 0xc00009e0a0, 0xc00009e0b0, 0x1, 0x0, 0x0, ...)
        _cgo_gotypes.go:1599 +0x45 fp=0xc00013bce8 sp=0xc00013bcc0 pc=0x1001bb6e5
github.com/wamuir/graft/tensorflow.(*Session).Run.func1(0xc00013bed0?, 0x1?, 0x0?, {0xc00013bed0?, 0x1, 0x7fd0de8058d0?}, {0x0?, 0x0, 0x100222fe0?}, 0xc00009e0b8)
        /Users/.../go/pkg/mod/github.com/wamuir/graft@v0.7.0/tensorflow/session.go:150 +0x20e fp=0xc00013bd98 sp=0xc00013bce8 pc=0x1001c6a8e
github.com/wamuir/graft/tensorflow.(*Session).Run(0xc0000ac000, 0x0, {0xc00013bed0, 0x1, 0x1}, {0x0, 0x0, 0x0})
        /Users/.../go/pkg/mod/github.com/wamuir/graft@v0.7.0/tensorflow/session.go:150 +0x29c fp=0xc00013be60 sp=0xc00013bd98 pc=0x1001c66fc
main.main()
        /.../workspaces/tensorflow-image/main.go:23 +0x147 fp=0xc00013bf40 sp=0xc00013be60 pc=0x1001cd327
runtime.main()
        /usr/local/go/src/runtime/proc.go:267 +0x2bb fp=0xc00013bfe0 sp=0xc00013bf40 pc=0x10003d17b
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00013bfe8 sp=0xc00013bfe0 pc=0x1000692c1
```

and the used example code
```
package main

import (
	"fmt"
	tf "github.com/wamuir/graft/tensorflow"
	"github.com/wamuir/graft/tensorflow/op"
)

func main() {
	// Construct a graph with an operation that produces a string constant.
	s := op.NewScope()
	c := op.Const(s, "Hello from TensorFlow version "+tf.Version())
	graph, err := s.Finalize()
	if err != nil {
		panic(err)
	}

	// Execute the graph in a session.
	sess, err := tf.NewSession(graph, nil)
	if err != nil {
		panic(err)
	}
	output, err := sess.Run(nil, []tf.Output{c}, nil)
	if err != nil {
		panic(err)
	}
	fmt.Println(output[0].Value())
}
```

and go.mod
```
module tensorflow-image

go 1.21

require (
	github.com/wamuir/graft v0.7.0 // indirect
	google.golang.org/protobuf v1.31.0 // indirect
)
```

**Comment by wamuir** [comment]
I successfully tested the bindings (r0.7) using the macOS libtensorflow 2.15 build at https://www.tensorflow.org/install/lang_c.  I do not know how/what build of libtensorflow brew provides but I'm concerned that it may be the problem.  Could you try using TensorFlow's official/published build instead?

**Comment by nea** [comment]
Ahoy @wamuir 

I uninstalled my brew installation and followed the Google manual for mac. Installation worked, I can see it is there, but I have a linker issue right now `ld: unknown file type in '/usr/local/lib/libtensorflow.so.2.15.0'`which I first have to resolve and will get back.


Thanks

**Comment by wamuir** [comment]
I think you've extracted the linux libtensorflow archive, which comes with .so libraries.  You'll want to clean that out of /usr/local/lib and then install instead the macOS libtensorflow archive (has .dylib libraries)

**Comment by nea** [comment]
Geez, you are right... too much copy/paste on my end. Sorry! My Bad ^^# Thanks big time

**Comment by nea** [comment]
Ahoy @wamuir , to update you: with the correct lib from Tensorflow itself it worked, both in .c and .go.
I removed and tried homebrew again, and got the same segmentation fault as before. But with the self-setup it works.

Thanks for your time and sorry for the inconvenience
