### ISSUE TITLE
Can not Add Conv2D due to T attr

### ISSUE THREAD

**Issue by Moocow9m** [wamuir/graft#4]
Despite using the same DType(tf.Float) for the layers, Conv2D add failed with the attached error:
Version: v0.2.0

`panic: failed to add operation "Conv2D": Inconsistent values for attr 'T' DT_FLOAT vs. DT_RESOURCE while building NodeDef 'Conv2D' using Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_BFLOAT16, DT_FLOAT, DT_DOUBLE, DT_INT32]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID", "EXPLICIT"]; attr=explicit_paddings:list(int),default=[]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]; attr=dilations:list(int),default=[1, 1, 1, 1]>`

MRE:
```
const ImageSize = 244
const ImageChannels = 3
const BatchSize = 1
const Padding = "SAME"
const DType = tf.Float
func main() {
		s := op.NewScope()
		s.WithDevice("/gpu:0")
		out := op.Placeholder(s.SubScope("input"), DType, op.PlaceholderShape(tf.MakeShape(BatchSize, ImageSize, ImageSize, ImageChannels)))
		filters := op.VarHandleOp(s.SubScope("filters"), DType, tf.MakeShape(3, 3, ImageChannels, 64))
		out = op.Conv2D(s, out, filters, []int64{1, 1, 1, 1}, Padding, op.Conv2DUseCudnnOnGpu(true))

		//c := op.Const(s, "Hello from TensorFlow version "+tf.Version())
		graph, err := s.Finalize()
		if err != nil {
			panic(err)
		}
		panic(graph) //for compilation sake
}
```

**Comment by wamuir** [comment]
Is `op.VarHandleOp()` the correct choice here? It returns a tensor of type `resource` which I believe explains the error message.

**Comment by Moocow9m** [comment]
I see, thanks for the response
